/**
 * ─── French → Arabic UI dictionary ─────────────────────────────────────────────
 * Because the 30 page components hard-code French text (they don't call t()),
 * the auto-translate engine (see `autoTranslate.ts`) swaps rendered French text
 * for Arabic at runtime whenever the active language is `ar`.
 *
 * Keys are the EXACT visible French strings (whitespace-normalised: single
 * spaces, trimmed). Anything not present here is left untouched (graceful
 * fallback), so data values (names, numbers, references) are never altered.
 * ──────────────────────────────────────────────────────────────────────────────
 */

export const FR_AR: Record<string, string> = {
  // ── Actions / buttons ──────────────────────────────────────────────────────
  "Ajouter": "إضافة",
  "Ajouter un client": "إضافة عميل",
  "AJOUTER UN CLIENT": "إضافة عميل",
  "Modifier": "تعديل",
  "Supprimer": "حذف",
  "Enregistrer": "حفظ",
  "Enregistrer les modifications": "حفظ التعديلات",
  "Enregistrer les Modifications": "حفظ التعديلات",
  "Enregistrer Profil": "حفظ الملف",
  "Enregistrer un Règlement": "تسجيل تسوية",
  "Sauvegarder": "حفظ",
  "Annuler": "إلغاء",
  "✕ Annuler": "✕ إلغاء",
  "Confirmer": "تأكيد",
  "CONFIRMER PAIEMENT": "تأكيد الدفع",
  "Fermer": "إغلاق",
  "Fermer Formulaire": "إغلاق النموذج",
  "Fermer le formulaire": "إغلاق النموذج",
  "Voir": "عرض",
  "Voir Détails": "عرض التفاصيل",
  "Voir détails": "عرض التفاصيل",
  "Imprimer": "طباعة",
  "Imprimer Bon": "طباعة السند",
  "Oui, Imprimer": "نعم، طباعة",
  "Filtrer": "تصفية",
  "Filtres": "عوامل التصفية",
  "Rechercher": "بحث",
  "Recherche": "بحث",
  "Retirer": "إزالة",
  "Activer": "تفعيل",
  "ACTIVER LE COMPTE": "تفعيل الحساب",
  "Télécharger": "تنزيل",
  "Télécharger / Ouvrir": "تنزيل / فتح",
  "Ouvrir le PDF": "فتح PDF",
  "Appliquer": "تطبيق",
  "Appliquer TVA": "تطبيق الضريبة",
  "Valider & Enregistrer": "تأكيد وحفظ",
  "Suivant": "التالي",
  "Suivant →": "التالي ←",
  "← Retour": "→ رجوع",
  "Retour": "رجوع",
  "Marquer Payé": "تعليم كمدفوع",
  "Payer le reste": "دفع المتبقي",
  "Payer Dette": "دفع الدين",
  "Payer la Dette": "دفع الدين",
  "Recruter": "توظيف",
  "Créer Client": "إنشاء عميل",
  "Créer Nouveau Client": "إنشاء عميل جديد",
  "Créer un compte d'accès pour": "إنشاء حساب دخول لـ",
  "Comparer avec le stock actuel": "المقارنة مع المخزون الحالي",
  "Synchroniser les Stocks": "مزامنة المخزون",
  "Recalculer automatiquement": "إعادة الحساب تلقائيًا",
  "Vider le panier": "إفراغ السلة",
  "Ajouter une cuve": "إضافة خزان",
  "Ajouter Scan": "إضافة مسح",
  "Ajouter une photo de la facture": "إضافة صورة الفاتورة",
  "Encaisser la Vente": "تحصيل البيع",
  "Changer le Mot de Passe": "تغيير كلمة المرور",
  "Gérer les pistolets": "إدارة المسدسات",
  "Programmer le Rendez-vous": "برمجة الموعد",
  "PROGRAMMER LE RENDEZ-VOUS": "برمجة الموعد",
  "Enregistrer les données": "حفظ البيانات",

  // ── Statuses / states ──────────────────────────────────────────────────────
  "Actif": "نشط",
  "Inactif": "غير نشط",
  "Active": "نشطة",
  "Compte actif": "حساب نشط",
  "En service": "في الخدمة",
  "En Service": "في الخدمة",
  "En congé": "في إجازة",
  "En Congé": "في إجازة",
  "Congé": "إجازة",
  "Maintenance": "صيانة",
  "Hors service": "خارج الخدمة",
  "Ouverte": "مفتوحة",
  "Clôturée": "مغلقة",
  "Fermée": "مقفلة",
  "Planifiée": "مبرمجة",
  "En attente": "قيد الانتظار",
  "En attente livraison": "بانتظار التسليم",
  "Payé": "مدفوع",
  "Payée": "مدفوعة",
  "Payés": "مدفوعة",
  "Payées": "مدفوعة",
  "PAYÉ": "مدفوع",
  "Non Payé": "غير مدفوع",
  "Non payé": "غير مدفوع",
  "Partiel": "جزئي",
  "Dette partielle": "دين جزئي",
  "À payer": "للدفع",
  "à Payer": "للدفع",
  "Dette": "دين",
  "Dettes": "ديون",
  "En Dette": "مدين",
  "Reçu": "مستلم",
  "Comparé": "مقارَن",
  "Correction": "تصحيح",
  "Rupture": "نفاد",
  "Stock Faible": "مخزون منخفض",
  "Normal": "عادي",
  "EN RETARD": "متأخر",
  "À VENIR": "قادم",
  "Brigade Active": "فرقة نشطة",
  "Compte de Résultat (P&L)": "حساب النتيجة (الأرباح والخسائر)",

  // ── Shifts / brigade ───────────────────────────────────────────────────────
  "Matin": "صباح",
  "Soir": "مساء",
  "Nuit": "ليل",
  "Shift": "الفترة",
  "Quart": "الوردية",
  "Date & Shift": "التاريخ والفترة",
  "ID Brigade": "معرّف الفرقة",
  "Brigade": "فرقة",
  "Brigades": "الفرق",
  "Détail des Brigades": "تفاصيل الفرق",
  "Relevés par Brigade": "كشوفات حسب الفرقة",
  "Performance des Brigades": "أداء الفرق",
  "Aucune brigade": "لا توجد فرقة",
  "Aucune brigade active": "لا توجد فرقة نشطة",
  "Aucune brigade en cours": "لا توجد فرقة جارية",
  "Aucune brigade en attente": "لا توجد فرقة قيد الانتظار",
  "Supprimer la Brigade": "حذف الفرقة",
  "Historique Brigade": "سجل الفرقة",
  "Clôture": "إغلاق",

  // ── Payment modes / financial ──────────────────────────────────────────────
  "Espèces": "نقدًا",
  "Espèces (Cash)": "نقدًا",
  "Espèces Reçues": "النقد المستلم",
  "Cash": "نقدًا",
  "Comptant": "نقدًا",
  "Chèque": "شيك",
  "Crédit": "آجل",
  "Avance": "تسبيق",
  "Avances": "التسبيقات",
  "Mixte": "مختلط",
  "Virement": "تحويل",
  "Bon": "سند",
  "Bons": "سندات",
  "Solde": "الرصيد",
  "Solde Avance": "رصيد التسبيق",
  "Solde disponible": "الرصيد المتاح",
  "Solde Restant": "الرصيد المتبقي",
  "Avance disponible": "التسبيق المتاح",
  "Montant": "المبلغ",
  "Montant (DA)": "المبلغ (د.ج)",
  "Montant total": "المبلغ الإجمالي",
  "Montant à Payer": "المبلغ المستحق",
  "Montant Total À Payer": "المبلغ الإجمالي المستحق",
  "MONTANT TOTAL À PAYER": "المبلغ الإجمالي المستحق",
  "Montant Collecté": "المبلغ المحصّل",
  "Montant invalide": "مبلغ غير صالح",
  "Total": "المجموع",
  "Total DA": "المجموع د.ج",
  "Total HT": "المجموع دون ضريبة",
  "Total TTC": "المجموع بالضريبة",
  "Total Net": "الصافي الإجمالي",
  "Total Net:": "الصافي الإجمالي:",
  "Total Dû": "المبلغ المستحق",
  "Total Payé": "الإجمالي المدفوع",
  "Total Facturé": "الإجمالي المفوتر",
  "Total facturé": "الإجمالي المفوتر",
  "Total Encaissé :": "الإجمالي المحصّل :",
  "Total Réel Encaissé": "الإجمالي الفعلي المحصّل",
  "Total Achat": "إجمالي الشراء",
  "Total Achats": "إجمالي المشتريات",
  "Total Vente": "إجمالي البيع",
  "Sous-total HT": "المجموع الفرعي دون ضريبة",
  "Déjà Réglé": "المدفوع مسبقًا",
  "Reste à Régler": "المتبقي للتسوية",
  "Reste": "المتبقي",
  "Excédent": "فائض",
  "Gains": "الأرباح",
  "Bénéfice Net": "الربح الصافي",
  "Marge Brute": "الهامش الإجمالي",
  "Marge Nette": "الهامش الصافي",
  "Créances Clients": "ديون العملاء",
  "Créances": "الديون المستحقة",
  "Avances Clients": "تسبيقات العملاء",
  "Masse Salariale": "كتلة الأجور",
  "Dépenses Exploitation": "مصاريف التشغيل",
  "Dépenses Exploit.": "مصاريف التشغيل",
  "Recette": "الإيراد",
  "Recette (DA)": "الإيراد (د.ج)",
  "Recette Carburant": "إيراد الوقود",
  "Recette Magasin": "إيراد المتجر",
  "Recette Totale": "الإيراد الإجمالي",
  "Recette Théorique": "الإيراد النظري",
  "Chiffre d'Affaires": "رقم الأعمال",
  "CA Jour": "رقم أعمال اليوم",
  "Salaire": "الأجر",
  "Salaire:": "الأجر:",
  "Salaire de base": "الأجر الأساسي",
  "Salaire de Base": "الأجر الأساسي",
  "Salaire Base": "الأجر الأساسي",
  "Salaire Base (DA)": "الأجر الأساسي (د.ج)",
  "💰 Salaire de Base": "💰 الأجر الأساسي",
  "Net Payé": "الصافي المدفوع",
  "NET À PAYER": "الصافي المستحق",
  "📊 CALCUL NET À PAYER": "📊 حساب الصافي المستحق",
  "Acompte": "تسبيق",
  "Acomptes": "التسبيقات",
  "Acompte versé": "التسبيق المدفوع",
  "- Acomptes": "- التسبيقات",
  "🏦 Total Acomptes": "🏦 إجمالي التسبيقات",
  "Absence": "غياب",
  "Absences": "الغيابات",
  "- Absences": "- الغيابات",
  "❌ Total Absences": "❌ إجمالي الغيابات",
  "Total Acomptes": "إجمالي التسبيقات",
  "Total Absences": "إجمالي الغيابات",
  "Caisse": "الصندوق",
  "Mode": "الطريقة",
  "Mode:": "الطريقة:",
  "Mode Paiement": "طريقة الدفع",
  "Mode de Paiement": "طريقة الدفع",
  "💳 Mode Paiement": "💳 طريقة الدفع",
  "Mode de règlement": "طريقة التسوية",
  "Mode de Règlement": "طريقة التسوية",
  "💵 Espèces": "💵 نقدًا",
  "📋 Chèque": "📋 شيك",

  // ── Entities / navigation labels used inside pages ─────────────────────────
  "Client": "عميل",
  "Client:": "العميل:",
  "Clients": "العملاء",
  "Client Inconnu": "عميل غير معروف",
  "Client Facturé": "العميل المفوتر",
  "Nouveau Client": "عميل جديد",
  "Aucun client trouvé": "لم يتم العثور على عميل",
  "Aucun client": "لا يوجد عميل",
  "Supprimer un client": "حذف عميل",
  "Vente sans client": "بيع بدون عميل",
  "Fournisseur": "مورّد",
  "Fournisseurs": "الموردون",
  "Aucun fournisseur trouvé": "لم يتم العثور على مورّد",
  "Produit": "منتج",
  "Produits": "المنتجات",
  "Aucun produit trouvé": "لم يتم العثور على منتج",
  "Pompiste": "عامل مضخة",
  "Pompistes": "عمال المضخات",
  "Pompiste de Service": "عامل المضخة المناوب",
  "Pompiste de Piste": "عامل مضخة المسار",
  "Aucun pompiste": "لا يوجد عامل مضخة",
  "Aucun pompiste assigné": "لم يتم تعيين عامل مضخة",
  "Supprimer Pompiste": "حذف عامل المضخة",
  "Chef": "رئيس",
  "Chef de Brigade": "رئيس الفرقة",
  "Chef Brigade": "رئيس الفرقة",
  "👨‍💼 Chef de Brigade": "👨‍💼 رئيس الفرقة",
  "Chefs de Brigade": "رؤساء الفرق",
  "Aucun chef de brigade": "لا يوجد رئيس فرقة",
  "Supprimer Chef de Brigade": "حذف رئيس الفرقة",
  "Gérant": "مدير",
  "Gérants": "المدراء",
  "Gérant de Station": "مدير المحطة",
  "Aucun gérant": "لا يوجد مدير",
  "Supprimer Gérant": "حذف المدير",
  "Employé Magasin": "موظف المتجر",
  "Employé Magasin / Caisse": "موظف المتجر / الصندوق",
  "Employés Magasin": "موظفو المتجر",
  "Emp. Magasin": "موظف المتجر",
  "Aucun employé magasin": "لا يوجد موظف متجر",
  "Supprimer Employé": "حذف الموظف",
  "Chauffeur": "السائق",
  "Nouveau chauffeur": "سائق جديد",
  "Nom du chauffeur": "اسم السائق",
  "Supprimer le chauffeur": "حذف السائق",
  "Supprimer ce chauffeur": "حذف هذا السائق",
  "Administrateur": "مشرف",
  "Admin": "مشرف",
  "Utilisateur": "مستخدم",
  "Caissier": "أمين الصندوق",
  "Opérateur": "المشغّل",
  "Agents": "الأعوان",
  "Personnel": "الموظفون",
  "Tableau du Personnel Complet": "جدول الموظفين الكامل",

  // ── Nav / sections / pages ─────────────────────────────────────────────────
  "Tableau de Bord": "لوحة القيادة",
  "Opérations": "العمليات",
  "Carburant": "الوقود",
  "Magasin": "المتجر",
  "Contacts": "جهات الاتصال",
  "Finances": "المالية",
  "Analytique": "التحليلات",
  "Cuves": "الخزانات",
  "Cuve": "خزان",
  "Cuve Associée": "الخزان المرتبط",
  "🪣 Cuve Associée": "🪣 الخزان المرتبط",
  "Cuves / Tanks": "الخزانات",
  "Pompes": "المضخات",
  "Pompe": "مضخة",
  "Pistes": "المسارات",
  "Piste": "مسار",
  "Piste Assignée": "المسار المعيّن",
  "Pistolet": "مسدس",
  "Pistolets": "المسدسات",
  "Ventes Carburant": "مبيعات الوقود",
  "Vente Magasin": "بيع المتجر",
  "Ventes Magasin": "مبيعات المتجر",
  "Vente au détail": "البيع بالتجزئة",
  "Bons de Livraison": "سندات التسليم",
  "Bon de Livraison": "سند التسليم",
  "Nouveau Bon de Livraison": "سند تسليم جديد",
  "Modifier le Bon de Livraison": "تعديل سند التسليم",
  "Aucun bon de livraison": "لا يوجد سند تسليم",
  "Achats": "المشتريات",
  "Achats Carburant": "مشتريات الوقود",
  "Achats Magasin": "مشتريات المتجر",
  "Inventaire": "الجرد",
  "Inventaires": "عمليات الجرد",
  "Aucun inventaire": "لا يوجد جرد",
  "Dépenses": "المصاريف",
  "Fiche Journalière": "الورقة اليومية",
  "Statistiques": "الإحصائيات",
  "Rapports": "التقارير",
  "Paramètres": "الإعدادات",
  "Paramètres Système": "إعدادات النظام",
  "Mes Paiements": "مدفوعاتي",
  "Mon Compte": "حسابي",
  "Navigation": "التنقل",
  "Facture": "فاتورة",
  "Nouvelle Facture": "فاتورة جديدة",
  "Aucune facture": "لا توجد فاتورة",
  "Supprimer la facture": "حذف الفاتورة",
  "Nouveau Reçu": "إيصال جديد",
  "Supprimer le reçu": "حذف الإيصال",
  "Bon de Commande": "سند طلب",
  "Bon de commande créé": "تم إنشاء سند الطلب",
  "Commandes": "الطلبات",
  "Journal d'Activité": "سجل النشاط",
  "Historique": "السجل",
  "Historique des Paiements": "سجل المدفوعات",
  "Transactions": "المعاملات",
  "Paiement": "الدفع",
  "Paiements": "المدفوعات",
  "Règlement": "التسوية",

  // ── Table headers / field labels ───────────────────────────────────────────
  "Date": "التاريخ",
  "Date:": "التاريخ:",
  "Date de création": "تاريخ الإنشاء",
  "Date de la vente": "تاريخ البيع",
  "Date d'Embauche": "تاريخ التوظيف",
  "Date d'Échéance": "تاريخ الاستحقاق",
  "Date Règlement": "تاريخ التسوية",
  "Date BL *": "تاريخ السند *",
  "Échéance": "الاستحقاق",
  "Type": "النوع",
  "Type de Carburant": "نوع الوقود",
  "Type Carburant": "نوع الوقود",
  "Type de Client": "نوع العميل",
  "TYPE DE CLIENT": "نوع العميل",
  "Statut": "الحالة",
  "Status": "الحالة",
  "État": "الحالة",
  "Nom": "الاسم",
  "Nom Complet": "الاسم الكامل",
  "Nom d'utilisateur": "اسم المستخدم",
  "Nom du contact": "اسم جهة الاتصال",
  "Nom du client...": "اسم العميل...",
  "Prénom": "الاسم الأول",
  "Téléphone": "الهاتف",
  "TÉLÉPHONE": "الهاتف",
  "Email": "البريد الإلكتروني",
  "ADRESSE EMAIL": "البريد الإلكتروني",
  "Adresse": "العنوان",
  "Adresse postale complète": "العنوان البريدي الكامل",
  "CIN": "رقم البطاقة",
  "Référence": "المرجع",
  "Désignation": "التسمية",
  "Catégorie": "الفئة",
  "Marque": "العلامة",
  "Unité": "الوحدة",
  "Unit": "الوحدة",
  "Quantité": "الكمية",
  "Prix": "السعر",
  "Prix/L": "السعر/ل",
  "Prix / L": "السعر/ل",
  "Prix Unit.": "سعر الوحدة",
  "Prix Unitaire": "سعر الوحدة",
  "Prix d'Achat": "سعر الشراء",
  "Prix de Vente": "سعر البيع",
  "Litres": "لتر",
  "Litres Distribués": "اللترات الموزعة",
  "Volume": "الحجم",
  "Volume (L)": "الحجم (ل)",
  "Volume Total": "الحجم الإجمالي",
  "Volume Vendu": "الحجم المباع",
  "Volume Fin (L)": "الحجم النهائي (ل)",
  "Degrés": "الدرجات",
  "Capacité": "السعة",
  "Stock": "المخزون",
  "Stock Actuel": "المخزون الحالي",
  "Stock Système": "مخزون النظام",
  "Stock Min": "الحد الأدنى للمخزون",
  "Seuil Alerte": "عتبة التنبيه",
  "Sortie": "الخروج",
  "Écart": "الفارق",
  "Écart (L)": "الفارق (ل)",
  "Index": "المؤشر",
  "Index Actuel": "المؤشر الحالي",
  "Index Début": "مؤشر البداية",
  "Index Fin": "مؤشر النهاية",
  "Index Départ": "مؤشر الانطلاق",
  "Index Système": "مؤشر النظام",
  "Idx Début": "مؤشر البداية",
  "Idx Fin": "مؤشر النهاية",
  "Dernier Index": "آخر مؤشر",
  "Notes": "ملاحظات",
  "Note / Plaque": "ملاحظة / اللوحة",
  "Actions": "الإجراءات",
  "Période": "الفترة",
  "Mois": "الشهر",
  "Heure": "الساعة",
  "Heure Début": "ساعة البداية",
  "Minute": "الدقيقة",
  "Rotation": "الدوران",
  "Vendus": "المباعة",
  "Alerte": "تنبيه",
  "Marge": "الهامش",
  "Pourcentage": "النسبة المئوية",
  "Théorique": "نظري",
  "Détails": "التفاصيل",
  "Détails de la transaction": "تفاصيل المعاملة",
  "Informations": "المعلومات",
  "Résumé": "ملخص",
  "Résumé Financier": "الملخص المالي",
  "Chef:": "الرئيس:",
  "Article": "المادة",
  "Comptabilité": "المحاسبة",
  "Décalages": "الفوارق",
  "Justificatif": "المبرّر",
  "Coût/Retenue (DA)": "التكلفة/الاقتطاع (د.ج)",

  // ── Filters / generic selectors ────────────────────────────────────────────
  "Tous": "الكل",
  "Toutes": "الكل",
  "Tout": "الكل",
  "Tous les types": "كل الأنواع",
  "Tous les modes": "كل الطرق",
  "Tous les fournisseurs": "كل الموردين",
  "Toutes les catégories": "كل الفئات",
  "Sélectionner...": "اختر...",
  "-- Sélectionner Fournisseur ---": "--- اختر المورّد ---",
  "--- Sélectionner Fournisseur ---": "--- اختر المورّد ---",
  "--- Cuve ---": "--- خزان ---",
  "— Aucun —": "— لا شيء —",
  "Aucun": "لا شيء",
  "Aucune donnée": "لا توجد بيانات",
  "Aucun résultat": "لا توجد نتائج",
  "Aucun historique disponible": "لا يوجد سجل متاح",
  "Ce mois": "هذا الشهر",
  "Ce Mois": "هذا الشهر",
  "Cette semaine": "هذا الأسبوع",
  "Cette année": "هذه السنة",
  "Aujourd'hui": "اليوم",
  "Auto": "تلقائي",
  "(Auto)": "(تلقائي)",
  "(Optionnel)": "(اختياري)",
  "N/A": "غير متاح",
  "Non renseigné": "غير محدد",
  "Inconnu": "غير معروف",

  // ── Fuel / product types ───────────────────────────────────────────────────
  "Gasoil": "مازوت",
  "Super 95": "سوبر 95",
  "Calcul GPL (%)": "حساب غاز البترول (%)",
  "État des Cuves": "حالة الخزانات",
  "Niveaux des Cuves": "مستويات الخزانات",
  "Gestion des Cuves": "إدارة الخزانات",
  "Aucune cuve configurée": "لم يتم إعداد أي خزان",
  "Aucune cuve disponible": "لا يوجد خزان متاح",
  "Cuves en alerte": "خزانات في حالة تنبيه",

  // ── Client / worker form sections & labels ─────────────────────────────────
  "Informations Générales": "معلومات عامة",
  "Informations de Contact": "معلومات الاتصال",
  "Informations Professionnelles": "معلومات مهنية",
  "Informations Fiscales & Commerciales (Optionnel)": "معلومات جبائية وتجارية (اختياري)",
  "Identité Administrative": "الهوية الإدارية",
  "Conditions Financières": "الشروط المالية",
  "Coordonnées": "معلومات الاتصال",
  "Configuration": "الإعداد",
  "Embauche": "التوظيف",
  "Accès Application": "الوصول للتطبيق",
  "Autoriser la connexion": "السماح بالاتصال",
  "Mot de passe": "كلمة المرور",
  "Mot de passe actuel": "كلمة المرور الحالية",
  "Nouveau mot de passe": "كلمة المرور الجديدة",
  "Confirmer nouveau mot de passe": "تأكيد كلمة المرور الجديدة",
  "Particulier": "فرد",
  "Entreprise": "مؤسسة",
  "Gouvernement": "حكومة",
  "MODE DE PAIEMENT PAR DÉFAUT": "طريقة الدفع الافتراضية",
  "Plafond Crédit Autorisé (DA)": "سقف الائتمان المسموح (د.ج)",
  "Délai Contractuel de Règlement (Jours)": "أجل التسوية التعاقدي (أيام)",
  "Encours/Dette Initial (DA)": "الرصيد/الدين الأولي (د.ج)",
  "Versement Initial d'Avance (DA)": "الدفعة الأولية للتسبيق (د.ج)",
  "REGISTRE DE COMMERCE (RC)": "السجل التجاري",
  "Numéro de Chèque": "رقم الشيك",
  "N° Chèque": "رقم الشيك",
  "Numéro du chèque...": "رقم الشيك...",
  "Numéro du bon...": "رقم السند...",
  "Numéro BL": "رقم السند",
  "Numéro BL *": "رقم السند *",
  "Panier": "السلة",
  "Immatriculation": "الترقيم",

  // ── Empty-states / messages / toasts ───────────────────────────────────────
  "Aucun paiement enregistré": "لا توجد مدفوعات مسجّلة",
  "Aucune vente enregistrée": "لا توجد مبيعات مسجّلة",
  "Aucune vente carburant": "لا توجد مبيعات وقود",
  "Aucune vente magasin": "لا توجد مبيعات متجر",
  "Aucun acompte enregistré": "لا توجد تسبيقات مسجّلة",
  "Aucune absence enregistrée": "لا توجد غيابات مسجّلة",
  "Aucun modèle": "لا يوجد قالب",
  "L'historique est vide pour le moment": "السجل فارغ حاليًا",
  "Le nom est obligatoire": "الاسم إلزامي",
  "Nom et CIN obligatoires": "الاسم ورقم البطاقة إلزاميان",
  "Veuillez remplir tous les champs": "يرجى ملء جميع الحقول",
  "Les mots de passe ne correspondent pas": "كلمتا المرور غير متطابقتين",
  "Les mots de passe ne correspondent pas.": "كلمتا المرور غير متطابقتين.",
  "Stock insuffisant !": "المخزون غير كافٍ !",
  "Le solde d'avance de ce client est insuffisant.": "رصيد تسبيق هذا العميل غير كافٍ.",
  "Vente enregistrée avec succès !": "تم تسجيل البيع بنجاح !",
  "Acompte enregistré": "تم تسجيل التسبيق",
  "Absence enregistrée": "تم تسجيل الغياب",
  "Bon de livraison enregistré — Cuves mises à jour": "تم تسجيل سند التسليم — تم تحديث الخزانات",
  "Bon de livraison modifié avec succès": "تم تعديل سند التسليم بنجاح",
  "Bon de livraison supprimé": "تم حذف سند التسليم",
  "Rendez-vous marqué comme payé": "تم تعليم الموعد كمدفوع",
  "Le scan du Bon de Livraison est obligatoire": "مسح سند التسليم إلزامي",
  "Au moins un scan est obligatoire pour enregistrer.": "يلزم مسح واحد على الأقل للحفظ.",
  "Erreur lors de l'enregistrement": "خطأ أثناء الحفظ",
  "Ajustez vos filtres ou créez un nouveau client.": "عدّل عوامل التصفية أو أنشئ عميلًا جديدًا.",

  // ── Loading / progress ─────────────────────────────────────────────────────
  "Chargement...": "جار التحميل...",
  "Traitement...": "جارٍ المعالجة...",
  "ENREGISTREMENT...": "جارٍ الحفظ...",
  "ACTIVATION...": "جارٍ التفعيل...",

  // ── Report / statistics titles ─────────────────────────────────────────────
  "Volume & Recette par Pompe": "الحجم والإيراد حسب المضخة",
  "Encaissements Carburant par Mode": "تحصيلات الوقود حسب الطريقة",
  "Pompes & Compteurs": "المضخات والعدادات",
  "Ventes par Mode de Paiement": "المبيعات حسب طريقة الدفع",
  "Top Produits par Chiffre d'Affaires": "أفضل المنتجات حسب رقم الأعمال",
  "État du Stock Magasin": "حالة مخزون المتجر",
  "Clients avec Créances": "العملاء المدينون",
  "Clients avec Avances (Soldes Positifs)": "العملاء ذوو التسبيقات (أرصدة موجبة)",
  "Masse Salariale par Catégorie": "كتلة الأجور حسب الفئة",
  "Dépenses par Catégorie": "المصاريف حسب الفئة",
  "Flux de Trésorerie & Créances": "التدفق النقدي والديون",
  "Synthèse Financière Globale": "التركيب المالي الشامل",
  "Top 5 Clients Carburant (Période)": "أفضل 5 عملاء وقود (الفترة)",
  "Alertes Stock Magasin": "تنبيهات مخزون المتجر",
  "Comparaison Période vs Période Précédente": "مقارنة الفترة بالفترة السابقة",
  "Historique de Débit Carburants (Litres)": "سجل صبيب الوقود (لتر)",
  "Performance Pompes — Volume Distribué": "أداء المضخات — الحجم الموزع",
  "Ventes Magasin — Top Articles": "مبيعات المتجر — أفضل المواد",
  "Répartition du Chiffre d'Affaires": "توزيع رقم الأعمال",
  "Produits Sans Mouvement": "منتجات دون حركة",
  "RÉSULTAT NET ESTIMÉ": "النتيجة الصافية المقدّرة",
  "Comparaison": "مقارنة",
  "Comparaison Cuves / Pistolets": "مقارنة الخزانات / المسدسات",
  "Détails Pistolets": "تفاصيل المسدسات",

  // ── Misc common ────────────────────────────────────────────────────────────
  "Système de gestion": "نظام الإدارة",
  "Description": "الوصف",
  "Description / Motif": "الوصف / السبب",
  "Description (Optionnel)": "الوصف (اختياري)",
  "Remarques / Notes": "ملاحظات",
  "Notes / Instructions": "ملاحظات / تعليمات",
  "Logo": "الشعار",
  "Photo": "صورة",
  "Image de la facture (optionnel)": "صورة الفاتورة (اختياري)",
  "Scans du BL": "مسوحات السند",
  "Scanner le Bon de Livraison *": "مسح سند التسليم *",
  "Factures Jour": "فواتير اليوم",
  "Dettes Jour": "ديون اليوم",
  "Au": "إلى",
  "Présent": "حاضر",
  "Absent": "غائب",
  "Oui": "نعم",
  "Non": "لا",
  "Total modifiable manuellement": "المجموع قابل للتعديل يدويًا",
  "Total modifié manuellement": "تم تعديل المجموع يدويًا",
  "La date de création est automatique et non modifiable": "تاريخ الإنشاء تلقائي وغير قابل للتعديل",
  "La date de création est automatique et non modifiable.": "تاريخ الإنشاء تلقائي وغير قابل للتعديل.",
  "Saisie des données administratives et financières": "إدخال البيانات الإدارية والمالية",
  "Mise à jour des paramètres financiers": "تحديث الإعدادات المالية",
  "Paramètres de Décalage": "إعدادات الفارق",

  // ── Supplementary batch (search placeholders, labels, titles) ───────────────
  "Rechercher par nom ou CIN...": "بحث بالاسم أو رقم البطاقة...",
  "Rechercher par nom, téléphone, CIN...": "بحث بالاسم أو الهاتف أو رقم البطاقة...",
  "Rechercher par nom, CIN...": "بحث بالاسم أو رقم البطاقة...",
  "Rechercher par description ou mot-clé...": "بحث بالوصف أو كلمة مفتاحية...",
  "Rechercher par N° BL, ID ou fournisseur...": "بحث برقم السند أو المعرّف أو المورّد...",
  "Rechercher par N° ou ID...": "بحث بالرقم أو المعرّف...",
  "Rechercher par N°...": "بحث بالرقم...",
  "Rechercher un BL par N° ou ID...": "بحث عن سند برقمه أو معرّفه...",
  "Rechercher par N° reçu ou ID...": "بحث برقم الإيصال أو المعرّف...",
  "Rechercher une facture (Non Payé / Partiel)...": "بحث عن فاتورة (غير مدفوعة / جزئية)...",
  "Rechercher par ID, Facture, Fournisseur...": "بحث بالمعرّف أو الفاتورة أو المورّد...",
  "Rechercher par désignation ou référence...": "بحث بالتسمية أو المرجع...",
  "Rechercher par nom, code-barres...": "بحث بالاسم أو الباركود...",
  "Rechercher par nom, code ou référence…": "بحث بالاسم أو الرمز أو المرجع…",
  "Rechercher par nom, contact ou téléphone...": "بحث بالاسم أو جهة الاتصال أو الهاتف...",
  "Rechercher une pompe...": "بحث عن مضخة...",
  "Rechercher client...": "بحث عن عميل...",
  "Rechercher un client...": "بحث عن عميل...",
  "Rechercher client (nom / téléphone)": "بحث عن عميل (الاسم / الهاتف)",
  "Filtrer par N°...": "تصفية بالرقم...",
  "Chercher Ticket, Client, Pompe...": "بحث عن تذكرة أو عميل أو مضخة...",
  "Chercher une page, un worker, un client...": "بحث عن صفحة أو موظف أو عميل...",
  "Nom ou téléphone…": "الاسم أو الهاتف…",
  "Nom, référence ou code-barres…": "الاسم أو المرجع أو الباركود…",
  "Numéro…": "الرقم…",
  "Numéro...": "الرقم...",
  "Numéro du chèque…": "رقم الشيك…",
  "Numéro du bon…": "رقم السند…",
  "Saisir numéro du bon...": "أدخل رقم السند...",
  "Saisir numéro du chèque...": "أدخل رقم الشيك...",
  "Entrez vos notes...": "أدخل ملاحظاتك...",
  "Entrez vos notes facultatives...": "أدخل ملاحظاتك الاختيارية...",
  "Notes optionnelles...": "ملاحظات اختيارية...",
  "Notes additionnelles...": "ملاحظات إضافية...",
  "Notes libres sur cet inventaire…": "ملاحظات حرة حول هذا الجرد…",
  "Notes et commentaires...": "ملاحظات وتعليقات...",
  "Commentaires ou plaque d'immatriculation...": "تعليقات أو رقم الترقيم...",
  "Remarques optionnelles, plaque…": "ملاحظات اختيارية، اللوحة…",
  "Maladie, sans justificatif...": "مرض، بدون مبرّر...",
  "Minimum 6 caractères": "6 أحرف على الأقل",
  "Identifiant unique": "معرّف فريد",
  "Unité...": "الوحدة...",
  "Nom du client": "اسم العميل",
  "Numéro CIN ou ICE...": "رقم البطاقة أو ICE...",
  "Adresse postale...": "العنوان البريدي...",
  "N° Facture, Client...": "رقم الفاتورة، العميل...",
  "Chèque n°, Virement n°...": "رقم الشيك، رقم التحويل...",
  "Saisissez votre mot de passe actuel": "أدخل كلمة المرور الحالية",
  "Nom de la pompe (ex: Pompe Diesel 1)": "اسم المضخة",

  // Labels / headers
  "Fin": "النهاية",
  "Début": "البداية",
  "Entrée": "الدخول",
  "Sortie Cuve": "خروج الخزان",
  "Total Litres": "إجمالي اللترات",
  "Décalage": "الفارق",
  "En cours": "قيد الإنجاز",
  "Validé": "مُصادق",
  "Permissions": "الصلاحيات",
  "Modèles Permissions": "قوالب الصلاحيات",
  "Montant Total": "المبلغ الإجمالي",
  "Numéro Chèque": "رقم الشيك",
  "Livraisons": "التسليمات",
  "Chefs Brigade": "رؤساء الفرق",
  "Menu": "القائمة",
  "Créé par:": "أنشئ بواسطة:",
  "Créé par": "أنشئ بواسطة",
  "Ma Brigade": "فرقتي",
  "Mes Brigades": "فرقي",
  "Mon Travail": "عملي",
  "Tableau de bord": "لوحة القيادة",
  "Numéro Registre de Commerce": "رقم السجل التجاري",
  "Numéro d'Identification Fiscale": "رقم التعريف الجبائي",
  "Numéro d'Identification Statistique": "رقم التعريف الإحصائي",
  "N° Identification Fiscale": "رقم التعريف الجبائي",
  "N° Identification Statistique": "رقم التعريف الإحصائي",
  "Code Article d'imposition": "رمز مادة الضريبة",
  "Code Article": "رمز المادة",
  "ARTICLE IMPOSITION": "مادة الضريبة",
  "Accès": "الوصول",
  "Station": "المحطة",
  "Index fin": "مؤشر النهاية",
  "-Acomptes:": "-التسبيقات:",
  "-Absences:": "-الغيابات:",
  "Enregistrés": "مسجّلة",
  "Enregistrées": "مسجّلة",
  "Effectués": "منجزة",
  "Réinitialiser": "إعادة تعيين",
  "Pièce": "قطعة",
  "Nom catégorie": "اسم الفئة",
  "Nom marque": "اسم العلامة",
  "Masse Salariale (est.)": "كتلة الأجور (تقديري)",
  "Fournisseur *": "المورّد *",
  "Date d'échéance (paiement)": "تاريخ الاستحقاق (الدفع)",
  "Convertisseur°/L": "المحوّل °/ل",
  "Aucune cuve": "لا يوجد خزان",
  "Détail par Piste / Pompe / Pistolet": "التفصيل حسب المسار / المضخة / المسدس",
  "Numéro de contact": "رقم جهة الاتصال",
  "Planification des Rendez-vous": "برمجة المواعيد",
  "Transaction TPE": "معاملة الدفع الإلكتروني",

  // Titles / buttons
  "NOUVEL ACOMPTE": "تسبيق جديد",
  "NOUVELLE ABSENCE": "غياب جديد",
  "NOUVELLE DÉPENSE": "مصروف جديد",
  "NOUVEL INVENTAIRE": "جرد جديد",
  "NOUVELLE CUVE": "خزان جديد",
  "FORMULAIRE DE PAIEMENT": "نموذج الدفع",
  "CRÉER UN MODÈLE": "إنشاء قالب",
  "AJOUTER UN FOURNISSEUR": "إضافة مورّد",
  "VENTE COMPTANT": "بيع نقدي",
  "VENTE COMPTANT (SANS CLIENT)": "بيع نقدي (بدون عميل)",
  "A CREDIT": "بالآجل",
  "Vente à crédit": "بيع بالآجل",
  "Nouvelle Vente": "بيع جديد",
  "AVANCE CLIENT": "تسبيق العميل",
  "NOM OU RAISON SOCIALE *": "الاسم أو التسمية الاجتماعية *",
  "CIN / IDENTIFIANT REGISTRE": "رقم البطاقة / معرّف السجل",
  "ADRESSE DU DOMICILE / SIÈGE": "عنوان السكن / المقر",
  "✓ Enregistrer": "✓ حفظ",
  "✓ Vérifié": "✓ مُتحقق",
  "✓ Conforme": "✓ مطابق",
  "✗ Non conforme": "✗ غير مطابق",
  "Conforme": "مطابق",
  "Non conforme": "غير مطابق",
  "Non vérifié": "غير مُتحقق",
  "Imprimer Reçu": "طباعة الإيصال",

  // Actions / misc
  "Ignorer": "تجاهل",
  "Ignorer cette alerte": "تجاهل هذا التنبيه",
  "Alertes": "التنبيهات",
  "Afficher": "عرض",
  "Affiché": "معروض",
  "Consultation uniquement": "الاطلاع فقط",
  "Supprimer le bon de livraison": "حذف سند التسليم",
  "Supprimer cette catégorie": "حذف هذه الفئة",
  "Supprimer cette marque": "حذف هذه العلامة",
  "Supprimer cette unité": "حذف هذه الوحدة",
  "Supprimer un produit": "حذف منتج",
  "Supprimer l'Inventaire": "حذف الجرد",
  "Supprimer le modèle": "حذف القالب",
  "Supprimer un fournisseur": "حذف مورّد",
  "Supprimer la Cuve": "حذف الخزان",
  "Supprimer l'Achat magasin": "حذف شراء المتجر",
  "Pas de contact": "لا توجد جهة اتصال",
  "Nom d'utilisateur requis pour l'accès application": "اسم المستخدم مطلوب للوصول للتطبيق",
  "Mot de passe requis pour créer le compte d'accès": "كلمة المرور مطلوبة لإنشاء حساب الدخول",
  "Paiement comptant standard sans encours ni avance.": "دفع نقدي عادي دون رصيد أو تسبيق.",
  "⚠️ Cette piste est déjà assignée à un autre pompiste": "⚠️ هذا المسار معيّن مسبقًا لعامل مضخة آخر",
  "Détails Brigade": "تفاصيل الفرقة",
  "Comptabilisée": "تمت المحاسبة",
};
